### PR TITLE
update opencv, dockerfile, and add readme for details

### PR DESCRIPTION
**Pull request by chilijung**

### CODE REVIEW

**Comment by steeve** [comment]
Your pull request is the reason I love open source so much.

Thank you. Merged.

**Comment by steeve** [comment]
is it pushed on the docker index? if it is, you might want to add it into the README

**Comment by chilijung** [comment]
nope I haven't pushed to index

**Comment by chilijung** [comment]
do you want me pushed to docker index? I'll do that if you want. :)

**Comment by steeve** [comment]
Oh yeah that would be awesome :)

**Comment by chilijung** [comment]
I'm happy you like it :+1: I'll do it later then

**Pull request merged**
